#!/usr/bin/env python3
hostname = 'MTG'

if hostname == 'MTG':
	print('The hostname was found to be mtg')


#accept input from user
hostnameinput = input('What is your hostname? ')

#print out question

